import { Nunito } from "next/font/google"
import "./globals.css"
import 'bootstrap/dist/css/bootstrap.min.css'
import TopNavbar from "./components/Navbar"

const nunito= Nunito({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <TopNavbar />
        {children}
      </body>
    </html>
  );
}
