import { Alegreya } from "next/font/google";
import "./globals.css";

const alegreya = Alegreya({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alegreya.className}>{children}</body>
    </html>
  );
}
